# -*- coding: utf-8 -*-
"""coffee_shop_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ySDkWd6GfbS2UQmIFk3pgE-HyKI2ZVh
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import plotly.express as px
from sklearn.tree import plot_tree
from plotly.subplots import make_subplots
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from google.colab import drive
drive.mount('/content/drive')

"""Importing Dataset"""

df = pd.read_csv('/content/drive/MyDrive/DAML/coffee sales.csv')
df



df.info()

df.describe()

df.dropna()

# transaction_date to datetime format
df['transaction_date'] = pd.to_datetime(df['transaction_date'], errors='coerce')

# Replace 'Drinking Chocolate' with 'Drinking_Chocolate' in the 'product_category' column
df['product_category'] = df['product_category'].replace({'Drinking Chocolate': 'drinking_Chocolate'})

# Verifying the change
df['product_category'].unique()

df['product_type'] = df['product_type'].replace({'Green tea': 'Green_tea', 'Hot chocolate':'hot_chocolate', 'Black coffee': 'black_coffee', 'chocolate cake': 'chocolate_cake', 'Black tea': 'black_tea', 'Milk coffee': 'milk_coffee', 'Milk tea': 'milk_tea', 'Red velvet': 'red_velvet'})

df['product_type'].unique()

df = df.drop_duplicates()

"""Dropping Unnecessary Columns"""

df = df.drop(["transaction_id", "store_id"], axis=1)
df.head()

# Rename the column in the DataFrame
df.rename(columns={'product_size': 'Size'}, inplace=True)
df.rename(columns={'product_category': 'Category'}, inplace=True)
df.head()

#mapping product size
size_mapping= {
    'Small': 1,
    'Medium': 2,
    'Large': 3
    }
df["Size"] = df["Size"].map(size_mapping)
df.head()

df.isnull().sum()

df['product_type'].unique()
df['product_type'].value_counts()

def get_products_by_category(df, category):
    # Filter by category and get unique product types
    category_products = df[df['Category'] == category]['product_type'].unique().tolist()
    return category_products

categories = ['Coffee', 'Tea', 'Drinking Chocolate','Bakery']
for category in categories:
    product = get_products_by_category(df, category)
    print(f"{category} Products: {product}")

# Selecting numeric columns only
numeric_data = df.select_dtypes(include=['float64', 'int64'])

# Calculating the IQR for each numeric column
iqr_values = numeric_data.apply(lambda x: x.quantile(0.75) - x.quantile(0.25))

# Display the IQR values
print("Interquartile Range (IQR) for each numeric column:\n", iqr_values)

"""**Visualization**

1. Heatmap
"""

# Initialize a LabelEncoder instance
label_encoder = LabelEncoder()

# Encode categorical columns 'store_location', 'product_category', 'product_size'
df['Store_Location_Encoded'] = label_encoder.fit_transform(df['store_location'])
df['category_Encoded'] = label_encoder.fit_transform(df['Category'])
df['size_Encoded'] = label_encoder.fit_transform(df['Size'])

# Select the columns for correlation analysis
columns_for_corr = ['actual_price', 'product_qty', 'Store_Location_Encoded', 'category_Encoded', 'size_Encoded']
corr_df = df[columns_for_corr].corr()

# Create the heatmap
fig = px.imshow(corr_df,
                x=corr_df.columns,
                y=corr_df.columns,
                color_continuous_scale='plasma',
                zmin=-1, zmax=1,
                title='Correlation Heatmap (Selected Features)')

fig.update_layout(xaxis_tickangle=-45)
fig.show()

"""2."""

# Aggregate data by date to get daily total quantity sold
daily_sales = df.groupby('Category')['Size'].sum().reset_index()

# Line plot for Sales Trend Over Time
fig = px.line(daily_sales,
              x='Category',
              y='Size',
              title="Daily Sales Trend",
              labels={'Category': 'category', 'Size': 'size'})

fig.update_layout(xaxis_title='category', yaxis_title='size')
fig.show()

"""3. Boxplot"""

# Box plot for Prices by Product Type
fig = px.box(df,
             x='Category',
             y='Rating',
             title="Category by Rating",
             labels={'Category': 'category', 'Rating': 'rating'},
             color='Category')

fig.show()

"""4. Scatterplot"""

fig = px.scatter(df,
                 x='product_type',
                 y='actual_price',
                 color='Size',
                 opacity=0.7,
                 title="Product Type vs Cost")

fig.update_traces(marker_size=5)
fig.show()

"""5.Piechart"""

# Aggregate data by store location
location_sales = df.groupby('store_location')['product_qty'].sum().reset_index()

# Pie chart for Sales by Store Location
fig = px.pie(location_sales,
             names='store_location',
             values='product_qty',
             title="Sales by Store Location",
             hole=0.3)
# Creates a donut chart effect

fig.show()

"""6. Boxplot"""

fig = px.box(df,
             x="product_type",
             y="Rating",
             title="Product type vs Rating",
             color='Category')
fig.show()

"""7."""



df['Category'].unique()

#mapping product size
category_mapping= {
    'Coffee': 1,
    'Tea': 2,
    'drinking_Chocolate': 3,
    'Bakery': 4
    }
df["Category"] = df["Category"].map(category_mapping)
df.head()

# Define features and target
Features = df[['actual_price','Category', 'Size', 'product_qty']]
Target = df['actual_price']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(Features, Target, test_size=0.2, random_state=0)

# Gradient Boosting Regressor
gbr = GradientBoostingRegressor(n_estimators=300, learning_rate=0.2, max_depth=3, random_state=42, loss='squared_error')
gbr.fit(X_train, y_train)
y_pred_gbr = gbr.predict(X_test)

# Evaluation Metrics
mae_gbr = mean_absolute_error(y_test, y_pred_gbr)
r2_gbr = r2_score(y_test, y_pred_gbr)
print("Gradient Boosting Regressor - MAE:", mae_gbr)
print("R2 Score:", r2_gbr)

# Cross-validation for Gradient Boosting Regressor
cv_scores_r2_gbr = cross_val_score(gbr, Features, Target, cv=5, scoring='r2')
cv_scores_mae_gbr = cross_val_score(gbr, Features, Target, cv=5, scoring='neg_mean_absolute_error')
print("Cross-validation R2 for GBR:", cv_scores_r2_gbr.mean())
print("Cross-validation MAE for GBR:", -cv_scores_mae_gbr.mean())

# Visualize Actual vs Predicted for GBR
fig = px.scatter(x=y_test, y=y_pred_gbr, labels={'x': 'Actual Quantity', 'y': 'Predicted Quantity'}, title='Actual vs Predicted - Gradient Boosting')
fig.add_shape(type="line", x0=y_test.min(), y0=y_test.min(), x1=y_test.max(), y1=y_test.max(), line=dict(dash='dash'))
fig.show()

"""**Random Forest Regressor**"""

# Random Forest Regressor
rfr = RandomForestRegressor(n_estimators=300, max_depth=3, random_state=42)
rfr.fit(X_train, y_train)
y_pred_rfr = rfr.predict(X_test)

# Evaluation Metrics for Random Forest
mae_rfr = mean_absolute_error(y_test, y_pred_rfr)
r2_rfr = r2_score(y_test, y_pred_rfr)
print("Random Forest Regressor - MAE:", mae_rfr)
print("R2 Score:", r2_rfr)

# Cross-validation for Random Forest Regressor
cv_scores_r2_rfr = cross_val_score(rfr, Features, Target, cv=5, scoring='r2')
cv_scores_mae_rfr = cross_val_score(rfr, Features, Target, cv=5, scoring='neg_mean_absolute_error')
print("Cross-validation R2 for RFR:", cv_scores_r2_rfr.mean())
print("Cross-validation MAE for RFR:", -cv_scores_mae_rfr.mean())

# Visualize Actual vs Predicted for RFR
fig = px.scatter(x=y_test, y=y_pred_rfr, labels={'x': 'Actual Quantity', 'y': 'Predicted Quantity'}, title='Actual vs Predicted - Random Forest')
fig.add_shape(type="line", x0=y_test.min(), y0=y_test.min(), x1=y_test.max(), y1=y_test.max(), line=dict(dash='dash'))
fig.show()

# Plot the tree structure of the first estimator in Random Forest
plt.figure(figsize=(20, 10))
plot_tree(rfr.estimators_[0], filled=True, feature_names=Features.columns)
plt.show()

# Define features and target
X = df.drop(columns=['total_price'])  # Assuming 'total_price' is the target variable
y = df['total_price']

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define preprocessing for numeric and categorical features
numeric_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X.select_dtypes(include=['object']).columns

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ]
)

# Define Random Forest Regressor parameters and pipeline
rfr_params = {
    'n_estimators': 300,
    'max_depth': 3,
    'random_state': 42
}
rfr = RandomForestRegressor(**rfr_params)

# Create a pipeline with preprocessing and regressor
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', rfr)
])

# Fit the model
pipeline.fit(X_train, y_train)

# Predict on the test set
y_pred = pipeline.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("Test Set MAE:", mae)
print("Test Set R2:", r2)

# Perform cross-validation for R2 score
cv_scores_r2 = cross_val_score(pipeline, X, y, cv=5, scoring='r2')
print("Cross-validation R2 scores for Random Forest Regressor:", cv_scores_r2)
print("Mean R2 score:", cv_scores_r2.mean())

# Perform cross-validation for Mean Absolute Error
cv_scores_mae = cross_val_score(pipeline, X, y, cv=5, scoring='neg_mean_absolute_error')
cv_scores_mae = -cv_scores_mae  # Negate because scoring returns negative MAE
print("Cross-validation MAE scores for Random Forest Regressor:", cv_scores_mae)
print("Mean MAE score:", cv_scores_mae.mean())

import plotly.express as px

# Visualization of predicted vs actual costs after using Random Forest Regressor
fig_cost = px.scatter(x=y_test, y=y_pred, labels={'x': 'Actual Cost', 'y': 'Predicted Cost'}, title='Actual vs Predicted Cost')
fig_cost.add_shape(
    type="line",
    x0=y_test.min(),
    y0=y_test.min(),
    x1=y_test.max(),
    y1=y_test.max(),
    line=dict(color="Red", dash="dash"),
)
fig_cost.update_layout(paper_bgcolor="white")
fig_cost.show()

import plotly.graph_objs as go
from plotly.offline import iplot

# Aggregate data for total sales by transaction_date
df['transaction_date'] = pd.to_datetime(df['transaction_date'])
daily_sales =df.groupby('transaction_date')['total_price'].sum().reset_index()

# Initialize plot
fig = go.Figure(data=[go.Scatter(x=daily_sales['transaction_date'], y=daily_sales['total_price'], mode='lines+markers')])
fig.update_layout(title='Daily Total Sales',
                  xaxis_title='Transaction Date',
                  yaxis_title='Total Sales (Price)')

# Display the plot
iplot(fig)